# Generated by Django 2.2.6 on 2019-10-20 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('text', models.TextField(verbose_name='texto')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='publicar em')),
                ('language', models.CharField(default='en', max_length=2, verbose_name='idioma')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artigo EN',
                'verbose_name_plural': 'Artigos EN',
            },
        ),
        migrations.CreateModel(
            name='PostEs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('text', models.TextField(verbose_name='texto')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='publicar em')),
                ('language', models.CharField(default='es', max_length=2, verbose_name='idioma')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artigo ES',
                'verbose_name_plural': 'Artigos ES',
            },
        ),
        migrations.CreateModel(
            name='PostPt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('text', models.TextField(verbose_name='texto')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='criado em')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='publicar em')),
                ('language', models.CharField(default='pt-br', max_length=2, verbose_name='idioma')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_en', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_pt_en', to='blog.PostEn', verbose_name='Artigo em Inglês')),
                ('post_es', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_pt_es', to='blog.PostEs', verbose_name='Artigo em Espanhol')),
            ],
            options={
                'verbose_name': 'Artigo PT',
                'verbose_name_plural': 'Artigos PT',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
