# Generated by Django 2.2.6 on 2019-10-21 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191020_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posten',
            options={'verbose_name': 'Post EN', 'verbose_name_plural': 'Posts EN'},
        ),
        migrations.AlterModelOptions(
            name='postes',
            options={'verbose_name': 'Post ES', 'verbose_name_plural': 'Posts ES'},
        ),
        migrations.AlterModelOptions(
            name='postpt',
            options={'verbose_name': 'Post PT', 'verbose_name_plural': 'Posts PT'},
        ),
        migrations.AlterField(
            model_name='postpt',
            name='language',
            field=models.CharField(default='pt-br', max_length=5, verbose_name='idioma'),
        ),
        migrations.AlterField(
            model_name='postpt',
            name='post_en',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_pt_en', to='blog.PostEn', verbose_name='Post em Inglês'),
        ),
        migrations.AlterField(
            model_name='postpt',
            name='post_es',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_pt_es', to='blog.PostEs', verbose_name='Post em Espanhol'),
        ),
    ]
